name: Computerraria Tests
run-name: Trigger Computerraria Tests
on:
  push:
    paths:
      - '**.cs'
jobs:
  trigger:
    name: Send Repository Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Send curl event
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/misprit7/computerraria/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'

